# Generated by Django 5.0.6 on 2024-07-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_alter_form_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formApp.form'),
        ),
    ]
